FROM openjdk:8
COPY ./target/ScreenApp-0.0.1-SNAPSHOT.jar ScreenApp-0.0.1-SNAPSHOT.jar
MAINTAINER moh7traore@gmail.com 
ENTRYPOINT ["java","-jar","ScreenApp-0.0.1-SNAPSHOT.jar"]
EXPOSE 8080



